plugins {
    id 'java'
    id 'maven-publish'
}

base {
    archivesName = id
    libsDirectory = new File("builtjars/")
}

java {
    withSourcesJar()
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

test {
//    useJUnitPlatform()
//    failOnNoDiscoveredTests.set(false)
}

println("Gradle Java: ${JavaVersion.current()}")
println("Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}, Encoding: ${System.getProperty "file.encoding"}")

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url "https://repo.spongepowered.org/maven" }
}

dependencies {
    compileOnly 'net.java.dev.jna:jna:4.4.0'
    compileOnly 'net.java.dev.jna:platform:3.4.0'
    compileOnly 'org.apache.logging.log4j:log4j-api:2.25.1'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.25.1'

    // TEST DEPENDENCIES
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testImplementation 'org.apache.logging.log4j:log4j-api:2.25.1'
    testImplementation 'org.apache.logging.log4j:log4j-core:2.25.1'
    testImplementation "net.java.dev.jna:jna:5.17.0"
    testImplementation "net.java.dev.jna:jna-platform:5.17.0"
}

jar {
    manifest {
        attributes "Specification-Title": id
        attributes "Specification-Vendor": authors
        attributes "Specification-Version": version
        attributes "Implementation-Title": name
        attributes "Implementation-Version": version
        attributes "Implementation-Vendor": authors
        attributes "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = id
            version = version

            from components.java
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/${github}")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}